import { UserTest, columns } from '@/containers/TestOverviewTable';
import { DataTable } from '@/containers/DataTable';
import { getCurrentUser } from '@/lib/data/user';

export default async function TestsOverview() {
  const data: UserTest[] = (await getCurrentUser())?.contentProgress.tests;
  // const data: UserTest[] = [
  //   {
  //     testTitle: 'Math Test',
  //     numberOfTimesPassed: 10,
  //     numberOfTimesTaken: 15,
  //     numberOfQuestions: 20,
  //     isCompleted: true,
  //     lastTaken: '2024-03-20T08:00:00.000Z',
  //   },
  //   {
  //     testTitle: 'English Test',
  //     numberOfTimesPassed: 5,
  //     numberOfTimesTaken: 8,
  //     numberOfQuestions: 25,
  //     isCompleted: false,
  //     lastTaken: '2024-03-19T14:30:00.000Z',
  //   },
  //   {
  //     testTitle: 'Science Test',
  //     numberOfTimesPassed: 3,
  //     numberOfTimesTaken: 6,
  //     numberOfQuestions: 30,
  //     isCompleted: true,
  //     lastTaken: '2024-03-18T10:45:00.000Z',
  //   },
  //   {
  //     testTitle: 'History Test',
  //     numberOfTimesPassed: 8,
  //     numberOfTimesTaken: 12,
  //     numberOfQuestions: 15,
  //     isCompleted: false,
  //     lastTaken: '2024-03-17T20:15:00.000Z',
  //   },
  //   {
  //     testTitle: 'Geography Test',
  //     numberOfTimesPassed: 2,
  //     numberOfTimesTaken: 4,
  //     numberOfQuestions: 10,
  //     isCompleted: true,
  //     lastTaken: '2024-03-16T12:00:00.000Z',
  //   },
  //   {
  //     testTitle: 'Computer Science Test',
  //     numberOfTimesPassed: 6,
  //     numberOfTimesTaken: 10,
  //     numberOfQuestions: 18,
  //     isCompleted: false,
  //     lastTaken: '2024-03-15T16:20:00.000Z',
  //   },
  //   {
  //     testTitle: 'Art Test',
  //     numberOfTimesPassed: 4,
  //     numberOfTimesTaken: 7,
  //     numberOfQuestions: 22,
  //     isCompleted: true,
  //     lastTaken: '2024-03-14T09:10:00.000Z',
  //   },
  //   {
  //     testTitle: 'Music Test',
  //     numberOfTimesPassed: 7,
  //     numberOfTimesTaken: 11,
  //     numberOfQuestions: 27,
  //     isCompleted: false,
  //     lastTaken: '2024-03-13T13:45:00.000Z',
  //   },
  //   {
  //     testTitle: 'Physical Education Test',
  //     numberOfTimesPassed: 9,
  //     numberOfTimesTaken: 14,
  //     numberOfQuestions: 35,
  //     isCompleted: true,
  //     lastTaken: '2024-03-12T18:30:00.000Z',
  //   },
  //   {
  //     testTitle: 'Chemistry Test',
  //     numberOfTimesPassed: 1,
  //     numberOfTimesTaken: 3,
  //     numberOfQuestions: 12,
  //     isCompleted: false,
  //     lastTaken: '2024-03-11T22:05:00.000Z',
  //   },
  //   {
  //     testTitle: 'Biology Test',
  //     numberOfTimesPassed: 11,
  //     numberOfTimesTaken: 18,
  //     numberOfQuestions: 24,
  //     isCompleted: true,
  //     lastTaken: '2024-03-10T11:55:00.000Z',
  //   },
  //   {
  //     testTitle: 'Physics Test',
  //     numberOfTimesPassed: 13,
  //     numberOfTimesTaken: 20,
  //     numberOfQuestions: 28,
  //     isCompleted: false,
  //     lastTaken: '2024-03-09T17:40:00.000Z',
  //   },
  //   {
  //     testTitle: 'Literature Test',
  //     numberOfTimesPassed: 15,
  //     numberOfTimesTaken: 22,
  //     numberOfQuestions: 32,
  //     isCompleted: true,
  //     lastTaken: '2024-03-08T08:25:00.000Z',
  //   },
  //   {
  //     testTitle: 'Economics Test',
  //     numberOfTimesPassed: 17,
  //     numberOfTimesTaken: 25,
  //     numberOfQuestions: 37,
  //     isCompleted: false,
  //     lastTaken: '2024-03-07T14:15:00.000Z',
  //   },
  //   {
  //     testTitle: 'Psychology Test',
  //     numberOfTimesPassed: 20,
  //     numberOfTimesTaken: 30,
  //     numberOfQuestions: 40,
  //     isCompleted: true,
  //     lastTaken: '2024-03-06T19:00:00.000Z',
  //   },
  //   {
  //     testTitle: 'Sociology Test',
  //     numberOfTimesPassed: 19,
  //     numberOfTimesTaken: 28,
  //     numberOfQuestions: 38,
  //     isCompleted: false,
  //     lastTaken: '2024-03-05T09:40:00.000Z',
  //   },
  //   {
  //     testTitle: 'Political Science Test',
  //     numberOfTimesPassed: 18,
  //     numberOfTimesTaken: 26,
  //     numberOfQuestions: 36,
  //     isCompleted: true,
  //     lastTaken: '2024-03-04T16:30:00.000Z',
  //   },
  //   {
  //     testTitle: 'Philosophy Test',
  //     numberOfTimesPassed: 16,
  //     numberOfTimesTaken: 24,
  //     numberOfQuestions: 34,
  //     isCompleted: false,
  //     lastTaken: '2024-03-03T08:20:00.000Z',
  //   },
  //   {
  //     testTitle: 'Religious Studies Test',
  //     numberOfTimesPassed: 14,
  //     numberOfTimesTaken: 21,
  //     numberOfQuestions: 31,
  //     isCompleted: true,
  //     lastTaken: '2024-03-02T13:10:00.000Z',
  //   },
  //   {
  //     testTitle: 'Environmental Science Test',
  //     numberOfTimesPassed: 12,
  //     numberOfTimesTaken: 19,
  //     numberOfQuestions: 29,
  //     isCompleted: false,
  //     lastTaken: '2024-03-01T18:00:00.000Z',
  //   },
  //   {
  //     testTitle: 'Foreign Language Test',
  //     numberOfTimesPassed: 23,
  //     numberOfTimesTaken: 35,
  //     numberOfQuestions: 45,
  //     isCompleted: true,
  //     lastTaken: '2024-02-29T09:45:00.000Z',
  //   },
  //   {
  //     testTitle: 'Health Education Test',
  //     numberOfTimesPassed: 22,
  //     numberOfTimesTaken: 33,
  //     numberOfQuestions: 42,
  //     isCompleted: false,
  //     lastTaken: '2024-02-28T15:30:00.000Z',
  //   },
  // ];

  return (
    <div className='flex items-center mx-auto py-10 overflow-hidden'>
      {data ? <DataTable columns={columns} data={data} /> : <span>Login to see your data</span>}
    </div>
  );
}
